---
title: "R Notebook"
output: html_notebook
---

# Chapter 3 - Vectors

## 3.2 Atomic vectors
### 3.2.5 Exercises
```{r 3.2.5.1}
?raw
xx <- raw(2)

```

```{r 3.2.5.2}
c(1, FALSE)
c("a", 1)
c(TRUE, 1L)

```

```{r 3.2.5.3}

```

## 3.3 Attributes
```{r}
a <- 1:4
attr(a, "x") <- "abcdef"
attr(a, "x")

attr(a, "y") <- 4:6
str(attributes(a))

a <- structure(
  1:4,
  x = "abcdef",
  y = 4:6
)
str(attributes(a))
```

### 3.3.4 Exercises
```{r 3.3.4.1}
setNames
unname
```

```{r 3.3.4.2}
x <- 1:10
# return NULL
nrow(x)
#> NULL
ncol(x)
#> NULL

# Pretend it's a column-vector
NROW(x)
#> [1] 10
NCOL(x)
#> [1] 1
```

```{r 3.3.4.3}
x1 <- array(1:5, c(1, 1, 5))  # 1 row,  1 column,  5 in third dimension
x2 <- array(1:5, c(1, 5, 1))  # 1 row,  5 columns, 1 in third dimension
x3 <- array(1:5, c(5, 1, 1))  # 5 rows, 1 column,  1 in third dimension
```

```{r 3.3.4.4}
structure(1:5, comment = "my attribute")
#> [1] 1 2 3 4 5
```

Contrary to other attributes, the comment is not printed (by print or print.default).

```{r}
foo <- structure(1:5, comment = "my attribute")

attributes(foo)
#> $comment
#> [1] "my attribute"
attr(foo, which = "comment")
#> [1] "my attribute"
```
















